name: Playwright Tests

on:
  push:
    branches: [ main, master, Ait-Branch]
  pull_request:
    branches: [ main, master, Ait-Branch]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install backend dependencies
      working-directory: ./Wanderly/backend
      run: pip install -r requirements.txt

    - name: Install frontend dependencies
      working-directory: ./Wanderly
      run: npm ci

    - name: Install QA test dependencies
      working-directory: ./Wanderly/QA
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: ./Wanderly/QA
      run: npx playwright install --with-deps

    - name: Setup Service Account Key
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > ./Wanderly/backend/serviceAccountKey.json

    - name: Setup .env
      run: |
        echo "${{ secrets.ENV_CONTENT }}" > ./Wanderly/.env


    - name: Start backend server
      working-directory: ./Wanderly/backend
      run: |
        nohup python -m uvicorn main:app --host 127.0.0.1 --port 8000 &

    - name: Start frontend server
      working-directory: ./Wanderly
      run: |
        nohup npm start -c &

    - name: Wait for frontend to be ready
      run: npx wait-on http://localhost:8081

    - name: Run Playwright tests
      working-directory: ./Wanderly/QA
      run: npx playwright test

    - name: Upload Playwright report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: Wanderly/QA/playwright-report/
        retention-days: 30
